name: buildFromAURWeekly

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
#  push:
#  pull_request:
  schedule:
    - cron:  '0 0 * * 5'

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [howdy, python-dlib, pam-python, python-face_recognition, python-face_recognition_models, microsoft-edge-stable-bin, google-chrome]

      fail-fast: false
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.ci-aur
        with:
          repo-name: ${{ matrix.repos }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "Built-from-AUR"
          artifacts: "./*/*pkg.tar*"
          token: ${{ secrets.GITHUB_TOKEN }}
