name: buildFromAUR

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  buildAUR:
    strategy:
      matrix:
        repos: [qv2ray-git]
      
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: ./.ci-aur
        with:
          repo-name: ${{ matrix.repos }}

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: "Built-from-AUR"
          artifacts: "./*/*pkg.tar*"
          token: ${{ secrets.GITHUB_TOKEN }}
